import tempfile
import unittest
from pathlib import Path
from unittest.mock import Mock

from tracker import AIGrouper


class FollowUpTemplateSelectionTests(unittest.TestCase):
    def _build_ai_grouper(self, temp_dir: str) -> AIGrouper:
        grouper = AIGrouper.__new__(AIGrouper)
        grouper._config = {
            "templates": {
                "follow_up": str(Path(temp_dir) / "follow_up.txt"),
                "follow_up_second": str(Path(temp_dir) / "follow_up_second.txt"),
            }
        }
        grouper._resolve_outreach_company_name = Mock(return_value="Acme")
        grouper._resolve_outreach_salutation_name = Mock(return_value="Jordan")
        grouper._call = Mock(
            return_value="Subject: Gemini fallback\n\nGenerated by Gemini."
        )
        grouper._split_subject_body = AIGrouper._split_subject_body
        return grouper

    def test_first_follow_up_uses_primary_template(self) -> None:
        with tempfile.TemporaryDirectory() as temp_dir:
            Path(temp_dir, "follow_up.txt").write_text(
                "Subject: First template\n\nPrimary body for {{company}}.",
                encoding="utf-8",
            )
            Path(temp_dir, "follow_up_second.txt").write_text(
                "Subject: Second template\n\nSecondary body for {{company}}.",
                encoding="utf-8",
            )
            grouper = self._build_ai_grouper(temp_dir)

            subject, body = grouper.generate_follow_up({}, "Omer", 1)

            self.assertEqual(subject, "First template")
            self.assertEqual(body, "Primary body for Acme.")
            grouper._call.assert_not_called()

    def test_second_follow_up_and_onward_uses_second_template(self) -> None:
        with tempfile.TemporaryDirectory() as temp_dir:
            Path(temp_dir, "follow_up.txt").write_text(
                "Subject: First template\n\nPrimary body for {{company}}.",
                encoding="utf-8",
            )
            Path(temp_dir, "follow_up_second.txt").write_text(
                "Subject: Second template\n\nSecondary body for {{company}}.",
                encoding="utf-8",
            )
            grouper = self._build_ai_grouper(temp_dir)

            subject, body = grouper.generate_follow_up({}, "Omer", 3)

            self.assertEqual(subject, "Second template")
            self.assertEqual(body, "Secondary body for Acme.")
            grouper._call.assert_not_called()

    def test_second_follow_up_falls_back_to_gemini_when_second_template_missing(self) -> None:
        with tempfile.TemporaryDirectory() as temp_dir:
            Path(temp_dir, "follow_up.txt").write_text(
                "Subject: First template\n\nPrimary body for {{company}}.",
                encoding="utf-8",
            )
            grouper = self._build_ai_grouper(temp_dir)

            subject, body = grouper.generate_follow_up({"role": "Engineer"}, "Omer", 2)

            self.assertEqual(subject, "Gemini fallback")
            self.assertEqual(body, "Generated by Gemini.")
            grouper._call.assert_called_once()


if __name__ == "__main__":
    unittest.main()
